### ISSUE TITLE
Tesseract installer on Ubuntu is a different package name

### ISSUE THREAD

**Issue by cfrichotsfdc** [ninp0/csi#1]
There's a few references to `sudo apt-get install tesseract-ocr-all`, these should be `tesseract-ocr`. (At least on my version of Ubuntu)

Also, it may be worth mentioning in the docs that the RVM installation method you're using is the Multi-User. The regular RVM install won't work with the `./install.sh ruby-gem` on Ubuntu.

**Comment by ninp0** [comment]
Greetings Christian,

Thanks for the surfacing this concern...what Ubuntu version are you using?
Here's what I see on my end:

$ sudo apt-cache search tesseract-ocr-all
tesseract-ocr-all - Tesseract OCR with all language packages

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04.1 LTS
Release: 16.04
Codename: xenial

As far as RVM goes, that's great feedback.  I'll be sure to mention a
multi-user install of RVM is a requirement, considering certain
circumstances in which elevated access is required while also using the CSI
gemset (e.g. using OS detection using the CSI::Plugins::NmapIt module, etc).

I hope that helps - let me know if you have any additional
questions/concerns.  Thanks!

**Comment by cfrichotsfdc** [comment]
Yep, looks like that particular box I was playing around with was Ubuntu 14.04 LTS :(

Awesome tool though - keen to keep on looking

**Comment by ninp0** [comment]
Thanks!

Yep, give it a shot - it has a ton of various capabilities...fyi, I also
updated the README.md per your feedback.  Thanks for reaching out about
this and let me know if you have additional feedback around making this
framework better!

Cheers
