### ISSUE TITLE
./install.sh virtualbox Using Kali box has issues w/ setting hostname

### ISSUE THREAD

**Issue by ninp0** [ninp0/csi#4]
$ sudo ./install.sh virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'sfoger/kali' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'sfoger/kali'
    default: URL: https://atlas.hashicorp.com/sfoger/kali
==> default: Adding box 'sfoger/kali' (v1.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/sfoger/boxes/kali/versions/1.0/providers/virtualbox.box
==> default: Successfully added box 'sfoger/kali' (v1.0) for 'virtualbox'!
==> default: Importing base box 'sfoger/kali'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'sfoger/kali' is up to date...
==> default: Setting the name of the VM: csi_default_1498167210199_53708
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
Vagrant attempted to execute the capability 'change_host_name'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.

**Comment by spyd3r** [comment]
Issue has been addressed by assigning the vm.guest property the value of :debian

**Comment by ninp0** [comment]
https://github.com/ninp0/csi/blob/master/Vagrantfile#L45
