### ISSUE TITLE
./deploy_packer_box.sh kali_rolling_virtualbox.json failure

### ISSUE THREAD

**Issue by spyd3r** [ninp0/csi#5]
/deploy_packer_box.sh kali_rolling_virtualbox.json 
rm: kali_rolling_virtualbox.box: No such file or directory
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://cdimage.kali.org/kali-2017.1/kali-linux-2017.1-amd64.iso
    virtualbox-iso: Download progress: 100%
==> virtualbox-iso: Starting HTTP server on port 8653
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3054)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1498368766 --memory 1024
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1498368766 --cpus 1
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 3s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Connected to SSH!
==> virtualbox-iso: Uploading VirtualBox version info (5.1.22)
==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
==> virtualbox-iso: Pausing 9s before the next provisioner...
==> virtualbox-iso: Provisioning with shell script: provisioners/pack_virtualbox.sh
    virtualbox-iso: Updating /etc/sudoers...
    virtualbox-iso: /tmp/script_3876.sh: line 3: /etc/sudoers.d/kalicsi: Permission denied
    virtualbox-iso: chmod: cannot access '/etc/sudoers.d/kalicsi': No such file or directory
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.

**Comment by spyd3r** [comment]
Per the example covered at http://blog.endpoint.com/2014/03/provisioning-development-environment_14.html, I setup the following provisioner to achieve adding the vagrant user to a sudoers.d file

{
      "type": "shell",
      "execute_command": "echo '{{user `kalicsi_pass`}}' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "inline": [
        "echo 'vagrant ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/kalicsi"
      ]
    },
    {
      "type": "shell",
      "execute_command": "echo '{{user `kalicsi_pass`}}' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "inline": "chmod 440 /etc/sudoers.d/kalicsi"
    }

Note* 
I am passing the kalicsi_pass variable in with the packer build command, like so:
packer build -force -only virtualbox-iso -var 'kalicsi_pass=password goes here'

**Comment by ninp0** [comment]
This has been fixed: https://github.com/ninp0/csi/blob/master/packer/http/kali_rolling_preseed.cfg#L76
