### ISSUE TITLE
Timeout while waiting for machine to shutdown

### ISSUE THREAD

**Issue by spyd3r** [ninp0/csi#6]
time ./deploy_packer_box.sh sfoger.json 
rm: kali_rolling_virtualbox.box: No such file or directory
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://cdimage.kali.org/kali-2017.1/kali-linux-2017.1-amd64.iso
==> virtualbox-iso: Starting HTTP server on port 8290
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2449)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1498425472 --memory 1024
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1498425472 --cpus 1
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 3s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Connected to SSH!
==> virtualbox-iso: Uploading VirtualBox version info (5.1.22)
==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
==> virtualbox-iso: Pausing 9s before the next provisioner...
==> virtualbox-iso: Provisioning with shell script: /var/folders/90/k4mvndls3yn9018nzgr9w8c00000gn/T/packer-shell611398491
    virtualbox-iso: running provisioner
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso:
    virtualbox-iso: We trust you have received the usual lecture from the local System
    virtualbox-iso: Administrator. It usually boils down to these three things:
    virtualbox-iso:
    virtualbox-iso: #1) Respect the privacy of others.
    virtualbox-iso: #2) Think before you type.
    virtualbox-iso: #3) With great power comes great responsibility.
    virtualbox-iso:
    virtualbox-iso: sudo: no tty present and no askpass program specified

==> virtualbox-iso: Timeout while waiting for machine to shut down.
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Timeout while waiting for machine to shut down.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Timeout while waiting for machine to shut down.

==> Builds finished but no artifacts were created.

real	17m23.774s
user	0m46.331s
sys	0m30.154s

The only difference with my sfoger.json packer definition is that I changed the provisioner to echo some text instead of running the script to update sudoers since that script is failing for me right now.

**Comment by spyd3r** [comment]
https://github.com/ninp0/csi/issues/5 is a direct cause of this failure. Without password-less sudo for vagrant in place, the shutdown command will not execute.

**Comment by ninp0** [comment]
This has been fixed and is working now: https://github.com/ninp0/csi/blob/master/packer/http/kali_rolling_preseed.cfg#L76
